"""
SAT-SA Evidence Intake.

This is the entry point of the evidence trust chain. It receives submitted
evidence (CSV, JSON, ZIP or any other regular file), establishes its identity
and provenance, and produces two physically separate artefacts:

    data/evidence/
        originals/<evidence_id>/<file>      preserved original, write-protected
        manifests/<evidence_id>.manifest.json
        provenance/<evidence_id>.provenance.json
        working/<evidence_id>/dataset/<file> controlled analysis copy
        working/<evidence_id>/package/...   validated extracted members

The analytical SAT-SA pipeline is expected to consume the *working copy*, never
the preserved original. Intake itself performs no SOC analysis and has no
knowledge of alerts, investigations, assets or any other SOC concept -- it only
establishes evidence integrity and provenance.

Controls implemented here:

* No network, cloud, external API or AI dependency. Pure local stdlib.
* Submitted files are only ever read as bytes. Nothing is executed, imported,
  evaluated, or treated as a command.
* Archives are never expanded with ``extractall``. Every member name is
  validated and resolved inside the workspace before anything is written.
* Absolute paths, drive letters, ``..`` traversal, symlink members, encrypted
  members and decompression bombs are rejected.
* Existing evidence is never overwritten; re-registering the same submission
  raises :class:`EvidenceConflictError`.
* Only metadata (names, sizes, digests, timestamps) is recorded. File contents
  are never logged or duplicated into the records.

Explicitly *not* claimed: locally stored evidence is not made physically
immutable, tamper-proof or administrator-proof. A preserved original is
write-protected at application level and registered with a SHA-256 fingerprint;
detection of later changes comes from comparing bytes against that fingerprint
before analysis. A privileged filesystem user can still modify both the evidence
and the local manifest. See ``docs/evidence_integrity.md``.
"""

from __future__ import annotations

import argparse
import re
import shutil
import stat
import sys
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Sequence, Union

from framework.evidence.integrity import (
    DEFAULT_CHUNK_SIZE,
    EvidenceConflictError,
    EvidenceError,
    EvidenceNotFoundError,
    EvidenceValidationError,
    IntegrityResult,
    IntegrityStatus,
    UnsafeArchiveError,
    calculate_sha256,
    copy_and_hash,
    verify_sha256,
)
from framework.evidence.manifest import (
    LOCATION_ORIGINALS,
    LOCATION_WORKING,
    MANIFEST_SUFFIX,
    EvidenceManifest,
    ManifestFile,
    build_manifest,
    classify_file,
    file_mtime_iso,
    generate_evidence_id,
    load_manifest,
    path_safe_name,
    resolve_within,
    save_manifest,
    utc_now,
    utc_now_iso,
)
from framework.evidence.provenance import (
    PROVENANCE_SUFFIX,
    STATUS_REGISTERED,
    ProvenanceRecord,
    build_provenance,
    load_provenance,
    save_provenance,
)

__all__ = [
    "DEFAULT_WORKSPACE_ROOT",
    "EvidenceIntake",
    "EvidenceIntegrityError",
    "EvidenceRecord",
    "EvidenceResolutionError",
    "EvidenceWorkspace",
    "ResolvedEvidence",
    "intake_file",
    "safe_member_name",
    "unlock_preserved_original",
    "validate_evidence_id",
    "validate_package",
    "main",
]


DEFAULT_WORKSPACE_ROOT = "data/evidence"

# Conservative archive limits. A legitimate SOC evidence package is orders of
# magnitude below these; they exist to bound a hostile or accidental bomb.
MAX_ARCHIVE_MEMBERS = 10_000
MAX_ARCHIVE_TOTAL_BYTES = 4 * 1024 * 1024 * 1024
MAX_ARCHIVE_MEMBER_BYTES = 1 * 1024 * 1024 * 1024
MAX_MEMBER_PATH_DEPTH = 32
MAX_MEMBER_NAME_LENGTH = 255

_WINDOWS_DRIVE = re.compile(r"\A[A-Za-z]:")

# An evidence ID is an opaque token generated by this package, never a path.
# It is validated against this pattern before it is ever joined to a
# directory, so a user-supplied ID cannot traverse, inject an absolute path,
# or select an arbitrary working copy.
_EVIDENCE_ID_PATTERN = re.compile(r"\A[A-Za-z0-9][A-Za-z0-9._-]{0,119}\Z")

_ENCRYPTED_FLAG = 0x1

_WORKING_COPY_DIRNAME = "dataset"
_PACKAGE_DIRNAME = "package"


# ---------------------------------------------------------------------------
# Analysis-resolution errors
# ---------------------------------------------------------------------------


class EvidenceResolutionError(EvidenceError):
    """Raised when an evidence ID cannot be resolved to a usable working copy."""


class EvidenceIntegrityError(EvidenceError):
    """Raised when registered evidence fails verification before analysis.

    The full comparison is carried on the exception so the caller can report
    the expected and observed digests without re-hashing anything.
    """

    def __init__(
        self,
        result: IntegrityResult,
        subject: str = "preserved original",
    ):
        self.result = result
        self.subject = subject

        super().__init__(
            f"{subject} failed integrity verification: {result.status.value}"
        )


def validate_evidence_id(evidence_id: Union[str, None]) -> str:
    """Validate an opaque evidence identifier.

    Rejects empty values, path separators, ``..``, absolute paths, drive
    letters, null bytes and anything outside the generated token alphabet.
    A rejected ID never reaches the filesystem.

    Raises:
        EvidenceNotFoundError: no identifier was supplied.
        EvidenceValidationError: the value is not a plain evidence token.
    """

    token = str(evidence_id if evidence_id is not None else "").strip()

    if not token:
        raise EvidenceNotFoundError("An evidence ID is required")

    if not _EVIDENCE_ID_PATTERN.match(token) or ".." in token:
        raise EvidenceValidationError(
            f"Refusing to resolve a value that is not an evidence "
            f"identifier: {evidence_id!r}"
        )

    return token


# ---------------------------------------------------------------------------
# Workspace layout
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class EvidenceWorkspace:
    """Filesystem layout of the evidence store.

    The store is a plain directory tree so an examiner can inspect it with
    ordinary tools. Nothing here is a database and nothing is required for
    verification beyond a preserved original and its manifest.
    """

    root: Path

    @classmethod
    def at(cls, root: Union[str, Path] = DEFAULT_WORKSPACE_ROOT) -> "EvidenceWorkspace":
        return cls(root=Path(root).expanduser())

    @property
    def originals_dir(self) -> Path:
        return self.root / "originals"

    @property
    def manifests_dir(self) -> Path:
        return self.root / "manifests"

    @property
    def provenance_dir(self) -> Path:
        return self.root / "provenance"

    @property
    def working_dir(self) -> Path:
        return self.root / "working"

    def evidence_dir(self, evidence_id: str) -> Path:
        return self.originals_dir / path_safe_name(evidence_id)

    def manifest_path(self, evidence_id: str) -> Path:
        return self.manifests_dir / (
            f"{path_safe_name(evidence_id)}{MANIFEST_SUFFIX}"
        )

    def provenance_path(self, evidence_id: str) -> Path:
        return self.provenance_dir / (
            f"{path_safe_name(evidence_id)}{PROVENANCE_SUFFIX}"
        )

    def working_copy_path(self, evidence_id: str, filename: str) -> Path:
        return (
            self.working_dir
            / path_safe_name(evidence_id)
            / _WORKING_COPY_DIRNAME
            / path_safe_name(filename)
        )

    def package_dir(self, evidence_id: str) -> Path:
        return (
            self.working_dir
            / path_safe_name(evidence_id)
            / _PACKAGE_DIRNAME
        )

    def ensure(self) -> "EvidenceWorkspace":
        """Create the directory skeleton if it is absent."""

        for directory in (
            self.root,
            self.originals_dir,
            self.manifests_dir,
            self.provenance_dir,
            self.working_dir,
        ):
            directory.mkdir(parents=True, exist_ok=True)

        return self

    def list_evidence_ids(self) -> list:
        """Registered evidence identifiers, newest first."""

        if not self.manifests_dir.is_dir():
            return []

        identifiers = [
            item.name[: -len(MANIFEST_SUFFIX)]
            for item in sorted(self.manifests_dir.glob(f"*{MANIFEST_SUFFIX}"))
            if item.is_file()
        ]

        return sorted(identifiers, reverse=True)


# ---------------------------------------------------------------------------
# Archive safety
# ---------------------------------------------------------------------------


def safe_member_name(name: str) -> str:
    """Validate an archive member name and return a safe relative path.

    Rejects absolute paths, Windows drive letters, ``..`` traversal, control
    characters, over-long names and over-deep nesting. Returns a normalised
    POSIX-style relative path that is guaranteed to stay inside the extraction
    directory.

    Raises:
        UnsafeArchiveError: the member name is not acceptable.
    """

    raw = str(name or "").strip()

    if not raw:
        raise UnsafeArchiveError("Archive member has an empty name")

    if "\x00" in raw:
        raise UnsafeArchiveError(
            f"Archive member name contains a null byte: {name!r}"
        )

    if any(ord(character) < 32 for character in raw):
        raise UnsafeArchiveError(
            f"Archive member name contains control characters: {name!r}"
        )

    # Treat a backslash as a separator for validation purposes: a Windows-style
    # name is only accepted if every one of its components is also safe.
    candidate = raw.replace("\\", "/")

    if candidate.startswith("/") or _WINDOWS_DRIVE.match(candidate):
        raise UnsafeArchiveError(
            f"Archive member uses an absolute path: {name!r}"
        )

    parts = [part for part in candidate.split("/") if part not in ("", ".")]

    if not parts:
        raise UnsafeArchiveError(
            f"Archive member does not name a file: {name!r}"
        )

    if any(part == ".." for part in parts):
        raise UnsafeArchiveError(
            f"Archive member attempts path traversal: {name!r}"
        )

    if len(parts) > MAX_MEMBER_PATH_DEPTH:
        raise UnsafeArchiveError(
            f"Archive member nesting is too deep ({len(parts)} levels): "
            f"{name!r}"
        )

    for part in parts:
        if len(part) > MAX_MEMBER_NAME_LENGTH:
            raise UnsafeArchiveError(
                f"Archive member name component is too long: {name!r}"
            )

    return "/".join(parts)


def validate_package(
    archive_path: Union[str, Path],
    max_members: int = MAX_ARCHIVE_MEMBERS,
    max_total_bytes: int = MAX_ARCHIVE_TOTAL_BYTES,
    max_member_bytes: int = MAX_ARCHIVE_MEMBER_BYTES,
) -> list:
    """Validate every member of a ZIP evidence package before any extraction.

    Returns a list of ``(ZipInfo, safe_relative_name)`` pairs. Raises before a
    single byte is written if anything is unsafe.

    Raises:
        UnsafeArchiveError: malformed archive, unsafe member, or a package that
            exceeds the member/byte limits.
    """

    source = Path(archive_path).expanduser()

    if not zipfile.is_zipfile(source):
        raise UnsafeArchiveError(f"Not a valid ZIP evidence package: {source}")

    try:
        with zipfile.ZipFile(source) as archive:
            bad_crc = archive.testzip()
    except (zipfile.BadZipFile, OSError, RuntimeError) as error:
        raise UnsafeArchiveError(
            f"Evidence package could not be opened: {source} ({error})"
        ) from error

    if bad_crc is not None:
        raise UnsafeArchiveError(
            f"Evidence package contains a corrupt member: {bad_crc!r}"
        )

    with zipfile.ZipFile(source) as archive:
        entries = archive.infolist()

        if len(entries) > max_members:
            raise UnsafeArchiveError(
                f"Evidence package declares {len(entries)} members, which "
                f"exceeds the limit of {max_members}"
            )

        declared_total = 0
        accepted: list = []

        for info in entries:
            if info.flag_bits & _ENCRYPTED_FLAG:
                raise UnsafeArchiveError(
                    f"Encrypted archive members are not supported: {info.filename!r}"
                )

            mode = info.external_attr >> 16

            if mode and stat.S_ISLNK(mode):
                raise UnsafeArchiveError(
                    f"Archive member is a symbolic link: {info.filename!r}"
                )

            safe = safe_member_name(info.filename)

            if info.is_dir():
                accepted.append((info, safe.rstrip("/")))
                continue

            if info.file_size > max_member_bytes:
                raise UnsafeArchiveError(
                    f"Archive member exceeds the {max_member_bytes} byte "
                    f"limit: {info.filename!r}"
                )

            declared_total += info.file_size

            if declared_total > max_total_bytes:
                raise UnsafeArchiveError(
                    "Evidence package exceeds the "
                    f"{max_total_bytes} byte uncompressed limit"
                )

            accepted.append((info, safe))

    return accepted


def _extract_package(
    archive_path: Union[str, Path],
    destination: Union[str, Path],
    accepted: Sequence,
) -> list:
    """Extract pre-validated members, one file at a time, inside destination.

    ``extractall`` is deliberately not used. Each member is written to a path
    produced by :func:`safe_member_name` and re-resolved against the extraction
    root, and each destination is opened in exclusive-create mode.
    """

    root = Path(destination).expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)

    written: list = []

    with zipfile.ZipFile(Path(archive_path).expanduser()) as archive:
        for info, safe in accepted:
            target = resolve_within(root, safe)

            if info.is_dir():
                target.mkdir(parents=True, exist_ok=True)
                continue

            target.parent.mkdir(parents=True, exist_ok=True)

            if target.exists():
                raise EvidenceConflictError(
                    f"Refusing to overwrite an extracted member: {target}"
                )

            written_bytes = 0

            with archive.open(info) as reader:
                with target.open("xb") as writer:
                    while True:
                        chunk = reader.read(DEFAULT_CHUNK_SIZE)

                        if not chunk:
                            break

                        written_bytes += len(chunk)

                        writer.write(chunk)

            written.append((safe, target, written_bytes))

    return written


# ---------------------------------------------------------------------------
# Intake result
# ---------------------------------------------------------------------------


@dataclass
class EvidenceRecord:
    """Everything intake established about a single submission."""

    evidence_id: str
    original_path: Path
    working_path: Path
    manifest: EvidenceManifest
    provenance: ProvenanceRecord
    integrity: IntegrityResult
    package_members: list = field(default_factory=list)
    workspace: Optional[EvidenceWorkspace] = None

    @property
    def verified(self) -> bool:
        return self.integrity.verified

    def to_dict(self) -> dict:
        return {
            "evidence_id": self.evidence_id,
            "original_path": str(self.original_path),
            "working_path": str(self.working_path),
            "originals_read_only": self.manifest.originals_read_only,
            "manifest": self.manifest.to_dict(),
            "provenance": self.provenance.to_dict(),
            "integrity": self.integrity.to_dict(),
            "package_members": [
                {"name": name, "size": size}
                for name, _, size in self.package_members
            ],
        }


@dataclass(frozen=True)
class ResolvedEvidence:
    """A registered submission resolved to a verified analysis target.

    Produced only after the preserved original has been verified against its
    registered digest. ``working_path`` is the artefact a downstream analytics
    layer may read; ``original_path`` is never handed out for analysis.
    """

    evidence_id: str
    original_path: Path
    working_path: Path
    manifest: EvidenceManifest
    provenance: Optional[ProvenanceRecord]
    original_integrity: IntegrityResult
    working_integrity: IntegrityResult

    @property
    def verified(self) -> bool:
        return (
            self.original_integrity.verified and self.working_integrity.verified
        )

    def to_dict(self) -> dict:
        return {
            "evidence_id": self.evidence_id,
            "original_path": str(self.original_path),
            "working_path": str(self.working_path),
            "original_integrity": self.original_integrity.to_dict(),
            "working_integrity": self.working_integrity.to_dict(),
        }


# ---------------------------------------------------------------------------
# Intake
# ---------------------------------------------------------------------------


class EvidenceIntake:
    """Register submitted evidence and produce a controlled analysis copy."""

    def __init__(
        self,
        root: Union[str, Path] = DEFAULT_WORKSPACE_ROOT,
    ):
        self.workspace = EvidenceWorkspace.at(root).ensure()

    # -- layout helpers ---------------------------------------------------

    @property
    def root(self) -> Path:
        return self.workspace.root

    def manifest_path(self, evidence_id: str) -> Path:
        return self.workspace.manifest_path(evidence_id)

    def provenance_path(self, evidence_id: str) -> Path:
        return self.workspace.provenance_path(evidence_id)

    # -- validation -------------------------------------------------------

    def validate_source(
        self,
        source: Union[str, Path],
        allow_symlink: bool = False,
    ) -> Path:
        """Validate a submitted path and return its resolved location."""

        path = Path(source).expanduser()

        if not path.exists():
            raise EvidenceNotFoundError(f"Evidence path not found: {path}")

        if path.is_symlink() and not allow_symlink:
            raise EvidenceValidationError(
                f"Evidence path is a symbolic link and was refused: {path}"
            )

        if not path.is_file():
            raise EvidenceValidationError(
                f"Evidence path is not a regular file: {path}"
            )

        resolved = path.resolve()

        originals_root = self.workspace.originals_dir.resolve()

        if resolved == originals_root or originals_root in resolved.parents:
            raise EvidenceValidationError(
                "Preserved evidence cannot be re-registered as a new "
                f"submission: {resolved}"
            )

        return resolved

    # -- registration -----------------------------------------------------

    def intake(
        self,
        source: Union[str, Path],
        source_identifier: Optional[str] = None,
        assessment_period: Optional[str] = None,
        submitted_by: Optional[str] = None,
        received_channel: Optional[str] = None,
        extract_package: bool = True,
        metadata: Optional[dict] = None,
        allow_symlink: bool = False,
        allow_duplicate: bool = False,
    ) -> EvidenceRecord:
        """Register one evidence file or ZIP package.

        Steps: validate path, inspect metadata, hash, reject a byte-identical
        re-submission, allocate an evidence ID, preserve the original, create
        the working copy, validate/extract a package if applicable, write
        manifest and provenance, then re-verify the preserved original against
        the recorded digest.

        Descriptive context (entity identifier, assessment period, submitter) is
        optional and is stored only if supplied.
        """

        received_at = utc_now()
        path = self.validate_source(source, allow_symlink=allow_symlink)

        observed_hash = calculate_sha256(path)
        size = path.stat().st_size
        stored_name = path_safe_name(path.name)
        content_type = classify_file(path)

        if not allow_duplicate:
            duplicate = self.find_registered_digest(observed_hash)

            if duplicate is not None:
                raise EvidenceConflictError(
                    "Byte-identical evidence is already registered as "
                    f"{duplicate['evidence_id']} (received "
                    f"{duplicate['created_at']}). An existing submission is "
                    "never replaced; verify the registered evidence instead, "
                    "or pass allow_duplicate=True to register a second copy."
                )

        evidence_id = self._allocate_evidence_id(observed_hash, received_at)

        working_path = self.workspace.working_copy_path(evidence_id, stored_name)

        manifest_file = self.manifest_path(evidence_id)
        provenance_file = self.provenance_path(evidence_id)
        evidence_dir = self.workspace.evidence_dir(evidence_id)

        try:
            original_path, read_only = self._preserve_original(
                path,
                evidence_dir,
                stored_name,
                observed_hash,
            )

            self._create_working_copy(original_path, working_path, observed_hash)

            package_members = self._register_package(
                path,
                evidence_id,
                content_type,
                extract_package=extract_package,
            )

            manifest = build_manifest(
                evidence_id=evidence_id,
                files=self._manifest_entries(
                    path=path,
                    stored_name=stored_name,
                    size=size,
                    sha256=observed_hash,
                    content_type=content_type,
                    package_members=package_members,
                ),
                created_at=utc_now_iso(),
                originals_read_only=read_only,
                notes={
                    "intake": "sat-sa-evidence-intake/1.0",
                    "original_filename": path.name,
                    "content_type": content_type,
                },
            )

            save_manifest(manifest, manifest_file)

            provenance = build_provenance(
                evidence_id=evidence_id,
                received_at=received_at.isoformat(timespec="seconds").replace(
                    "+00:00", "Z"
                ),
                original_filename=path.name,
                file_size=size,
                sha256=observed_hash,
                package_type=content_type,
                source_identifier=source_identifier,
                assessment_period=assessment_period,
                submitted_by=submitted_by,
                received_channel=received_channel,
                status=STATUS_REGISTERED,
                metadata=metadata,
            )

            provenance.add_custody_event(
                action="EVIDENCE_RECEIVED",
                detail=f"Registered {len(manifest.files)} file(s) from "
                f"{path.name}",
            )
            provenance.add_custody_event(
                action="ORIGINAL_PRESERVED",
                detail=f"Original evidence preserved; application-level write "
                f"protection enabled: {read_only}. This is a handling control, "
                f"not a cryptographic guarantee.",
            )
            provenance.add_custody_event(
                action="ANALYSIS_COPY_CREATED",
                detail=f"Working copy available for the SAT-SA pipeline: "
                f"{working_path}",
            )

            save_provenance(provenance, provenance_file)

            integrity = verify_sha256(original_path, manifest.files[0].sha256)

            if not integrity.verified:
                raise EvidenceValidationError(
                    "Preserved original failed immediate re-verification: "
                    f"{integrity.status.value}"
                )

        except Exception:
            self._discard(evidence_id)
            raise

        return EvidenceRecord(
            evidence_id=evidence_id,
            original_path=original_path,
            working_path=working_path,
            manifest=manifest,
            provenance=provenance,
            integrity=integrity,
            package_members=package_members,
            workspace=self.workspace,
        )

    # -- verification -----------------------------------------------------

    def verify(self, evidence_id: str) -> list:
        """Re-verify every registered file of a submission against its manifest.

        Returns one :class:`IntegrityResult` per manifest entry.
        """

        manifest = load_manifest(self.manifest_path(evidence_id))

        return manifest.verify(self.verification_roots(evidence_id))

    def verification_roots(self, evidence_id: str) -> dict:
        """Base directories a manifest's recorded locations resolve against."""

        identifier = path_safe_name(evidence_id)

        return {
            LOCATION_ORIGINALS: self.workspace.evidence_dir(identifier),
            LOCATION_WORKING: self.workspace.working_dir / identifier,
        }

    def verify_all(self) -> dict:
        """Re-verify every registered submission, keyed by evidence ID."""

        return {
            evidence_id: [
                result.to_dict()
                for result in self.verify(evidence_id)
            ]
            for evidence_id in self.workspace.list_evidence_ids()
        }

    def load_manifest(self, evidence_id: str) -> EvidenceManifest:
        return load_manifest(self.manifest_path(evidence_id))

    def find_registered_digest(self, sha256: str) -> Optional[dict]:
        """Locate an already registered submission with this exact digest.

        The evidence ID contains a timestamp, so identical content submitted
        later would receive a different identifier. Comparing digests is what
        makes duplicate detection independent of clock resolution.
        """

        for evidence_id in self.workspace.list_evidence_ids():
            try:
                manifest = load_manifest(self.manifest_path(evidence_id))
            except EvidenceError:
                continue

            for entry in manifest.files:
                if entry.role == "original" and entry.sha256 == sha256:
                    return {
                        "evidence_id": evidence_id,
                        "name": entry.name,
                        "created_at": manifest.created_at,
                    }

        return None

    def load_provenance(self, evidence_id: str) -> ProvenanceRecord:
        return load_provenance(self.provenance_path(evidence_id))

    # -- analysis resolution ----------------------------------------------

    def resolve_evidence_id(self, evidence_id: str) -> str:
        """Validate an evidence ID and confirm it is registered.

        This performs no analysis and no hashing: it only establishes that the
        identifier is a well-formed token and that a manifest exists for it.

        Raises:
            EvidenceNotFoundError: no identifier supplied, or nothing is
                registered under it.
            EvidenceValidationError: the value is not a plain evidence token.
        """

        identifier = validate_evidence_id(evidence_id)

        if not self.manifest_path(identifier).is_file():
            raise EvidenceNotFoundError(
                f"No evidence registration found for {identifier} in "
                f"{self.workspace.root}"
            )

        return identifier

    def verify_analysis_target(self, evidence_id: str) -> ResolvedEvidence:
        """Verify registered evidence and return its controlled working copy.

        Order of operations, all of it before any analysis may start:

        1. load the registered manifest for the (already validated) ID;
        2. verify the preserved original against its registered digest;
        3. resolve the working copy the workspace created at intake;
        4. verify the working copy still matches the registered digest.

        Any non-``VERIFIED`` outcome raises :class:`EvidenceIntegrityError`
        carrying the full comparison. The preserved original is never returned
        as an analysis target.

        Raises:
            EvidenceNotFoundError: the ID is not registered.
            EvidenceResolutionError: the registration is structurally unusable.
            EvidenceIntegrityError: verification did not succeed.
        """

        identifier = self.resolve_evidence_id(evidence_id)
        manifest = self.load_manifest(identifier)

        original_entry = next(
            (entry for entry in manifest.files if entry.role == "original"),
            None,
        )

        if original_entry is None:
            raise EvidenceResolutionError(
                f"{identifier} registers no preserved original"
            )

        original_path = resolve_within(
            self.workspace.evidence_dir(identifier),
            original_entry.relative_path,
        )

        original_integrity = verify_sha256(
            original_path, original_entry.sha256
        )

        if not original_integrity.verified:
            raise EvidenceIntegrityError(
                original_integrity, subject="preserved original"
            )

        working_path = resolve_within(
            self.workspace.working_dir / identifier,
            (
                Path(_WORKING_COPY_DIRNAME)
                / path_safe_name(original_entry.stored_name)
            ).as_posix(),
        )

        if not working_path.is_file():
            raise EvidenceResolutionError(
                f"{identifier} has no controlled working copy at "
                f"{working_path}; re-register the evidence before analysis"
            )

        working_integrity = verify_sha256(
            working_path, original_entry.sha256
        )

        if not working_integrity.verified:
            raise EvidenceIntegrityError(
                working_integrity, subject="controlled working copy"
            )

        try:
            provenance = self.load_provenance(identifier)
        except EvidenceError:
            provenance = None

        return ResolvedEvidence(
            evidence_id=identifier,
            original_path=original_path,
            working_path=working_path,
            manifest=manifest,
            provenance=provenance,
            original_integrity=original_integrity,
            working_integrity=working_integrity,
        )

    def resolve_analysis_target(self, evidence_id: str) -> ResolvedEvidence:
        """Convenience wrapper: validate, verify, and return the target."""

        return self.verify_analysis_target(evidence_id)

    def list_evidence(self) -> list:
        """Metadata-only inventory of registered submissions."""

        inventory: list = []

        for evidence_id in self.workspace.list_evidence_ids():
            entry = {"evidence_id": evidence_id}

            try:
                manifest = self.load_manifest(evidence_id)
            except EvidenceError:
                entry["status"] = IntegrityStatus.UNAVAILABLE.value
                inventory.append(entry)
                continue

            entry["created_at"] = manifest.created_at
            entry["file_count"] = manifest.file_count
            entry["total_size"] = manifest.total_size
            entry["files"] = [
                {
                    "name": item.name,
                    "size": item.size,
                    "sha256": item.sha256,
                    "content_type": item.content_type,
                }
                for item in manifest.files
            ]

            statuses = {
                result.status.value
                for result in self.verify(evidence_id)
            }

            entry["integrity"] = (
                "VERIFIED"
                if statuses == {IntegrityStatus.VERIFIED.value}
                else sorted(statuses)
            )

            inventory.append(entry)

        return inventory

    # -- internals --------------------------------------------------------

    def _allocate_evidence_id(
        self,
        sha256: str,
        received_at,
    ) -> str:
        """Return an evidence identifier that is not yet in use.

        The base identifier is derived from the digest and the registration
        moment, so it is normally free. If it is already taken -- two distinct
        submissions inside the same second, or an explicitly permitted
        duplicate -- a numeric suffix is appended rather than overwriting the
        existing registration.
        """

        base = generate_evidence_id(sha256, received_at)
        candidate = base
        attempt = 1

        while self._is_registered(candidate):
            attempt += 1
            candidate = f"{base}-{attempt}"

        return candidate

    def _is_registered(self, evidence_id: str) -> bool:
        return any(
            occupied.exists()
            for occupied in (
                self.workspace.evidence_dir(evidence_id),
                self.manifest_path(evidence_id),
                self.provenance_path(evidence_id),
            )
        )

    def _preserve_original(
        self,
        path: Path,
        evidence_dir: Path,
        stored_name: str,
        expected_hash: str,
    ) -> tuple:
        """Copy evidence into the originals area and protect it from writes.

        The copy is hashed as it is written, so the digest recorded later is the
        digest of the bytes actually on disk.
        """

        evidence_dir.mkdir(parents=True, exist_ok=True)

        destination = evidence_dir / stored_name

        if destination.exists():
            raise EvidenceConflictError(
                f"Refusing to overwrite existing original evidence: "
                f"{destination}"
            )

        written, copied_hash = copy_and_hash(path, destination)

        if copied_hash != expected_hash:
            raise EvidenceValidationError(
                "Evidence changed while it was being registered; the "
                "submission was rejected and nothing was preserved"
            )

        read_only = _set_read_only(destination)

        return destination, read_only

    def _create_working_copy(
        self,
        original_path: Path,
        working_path: Path,
        expected_hash: str,
    ) -> None:
        """Create the separate, writable analysis copy of the original.

        The working copy is the only artefact the SAT-SA pipeline is meant to
        read. It is deliberately a distinct file so that analysis can never
        alter the preserved original by accident.
        """

        working_path.parent.mkdir(parents=True, exist_ok=True)

        if working_path.exists():
            raise EvidenceConflictError(
                f"Refusing to overwrite an existing analysis copy: "
                f"{working_path}"
            )

        # A write-protected original is not opened for writing, so the copy is
        # made from the source bytes and re-checked against the digest.
        with open(working_path, "xb") as writer:
            with original_path.open("rb") as reader:
                shutil.copyfileobj(reader, writer, DEFAULT_CHUNK_SIZE)

        observed = calculate_sha256(working_path)

        if observed != expected_hash:
            working_path.unlink(missing_ok=True)
            raise EvidenceValidationError(
                "Working copy did not match the registered digest"
            )

    def _register_package(
        self,
        path: Path,
        evidence_id: str,
        content_type: str,
        extract_package: bool,
    ) -> list:
        """Validate a ZIP package and extract it into the working area.

        The package itself is already registered and hashed as the original;
        this step only handles the members it contains.
        """

        if content_type != "zip":
            return []

        accepted = validate_package(path)

        members: list = []

        if extract_package:
            destination = self.workspace.package_dir(evidence_id)
            members = _extract_package(path, destination, accepted)

        return members

    def _manifest_entries(
        self,
        path: Path,
        stored_name: str,
        size: int,
        sha256: str,
        content_type: str,
        package_members: Sequence,
    ) -> list:
        entries = [
            ManifestFile(
                name=path.name,
                stored_name=stored_name,
                relative_path=stored_name,
                size=int(size),
                sha256=sha256,
                modified_at=file_mtime_iso(path),
                content_type=content_type,
                role="original",
                location=LOCATION_ORIGINALS,
            )
        ]

        for name, target, written in package_members:
            relative = (
                Path(_PACKAGE_DIRNAME) / Path(name).as_posix()
            ).as_posix()

            entries.append(
                ManifestFile(
                    name=name,
                    stored_name=Path(name).name,
                    relative_path=relative,
                    size=int(written),
                    sha256=calculate_sha256(target),
                    modified_at=file_mtime_iso(target),
                    content_type=classify_file(target),
                    role="extracted",
                    location=LOCATION_WORKING,
                )
            )

        return entries

    def _discard(self, evidence_id: str) -> None:
        """Remove a partially written submission after a failed intake."""

        for directory in (
            self.workspace.evidence_dir(evidence_id),
            self.workspace.working_dir / path_safe_name(evidence_id),
        ):
            if not directory.exists():
                continue

            for path in sorted(directory.rglob("*"), reverse=True):
                try:
                    if path.is_file():
                        _set_writable(path)
                        path.unlink()
                    elif path.is_dir():
                        path.rmdir()
                except OSError:
                    pass

            try:
                directory.rmdir()
            except OSError:
                pass

        for record in (
            self.manifest_path(evidence_id),
            self.provenance_path(evidence_id),
        ):
            try:
                record.unlink(missing_ok=True)
            except OSError:
                pass


def _set_read_only(path: Path) -> bool:
    """Application-level write protection for a preserved original.

    This clears the owner write bit so a well-behaved process does not
    overwrite registered evidence by accident. It is a *handling control*, not
    a security boundary and not a cryptographic one: the owning account can
    restore the bit, and a privileged filesystem user can modify the evidence
    file and the local manifest that records its digest.

    The control that actually detects change is the registered SHA-256 digest,
    compared during verification. See ``docs/evidence_integrity.md``.
    """

    try:
        current = path.stat().st_mode
        path.chmod(stat.S_IMODE(current) & ~0o222)
        return True
    except OSError:
        return False


def _set_writable(path: Path) -> None:
    try:
        current = path.stat().st_mode
        path.chmod(stat.S_IMODE(current) | 0o200)
    except OSError:
        pass


def unlock_preserved_original(path: Union[str, Path]) -> Path:
    """Restore owner-write permission on a preserved original.

    Maintenance and demonstration only: an examiner may need to restore write
    access in order to prove that a recorded digest detects modification. This
    is deliberately an explicit, named action rather than something intake does
    automatically.
    """

    target = Path(path).expanduser()

    if not target.is_file():
        raise EvidenceNotFoundError(f"Evidence file not found: {target}")

    _set_writable(target)

    return target


def intake_file(
    source: Union[str, Path],
    root: Union[str, Path] = DEFAULT_WORKSPACE_ROOT,
    **options,
) -> EvidenceRecord:
    """Convenience wrapper: register one submission into a workspace."""

    return EvidenceIntake(root=root).intake(source, **options)

# ---------------------------------------------------------------------------
# Command line demonstration
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m framework.evidence.intake",
        description=(
            "SAT-SA evidence intake: register submitted evidence, verify its "
            "integrity, and create a controlled analysis copy."
        ),
    )

    subparsers = parser.add_subparsers(dest="command")

    intake_parser = subparsers.add_parser(
        "intake",
        help="register a submitted CSV/JSON/ZIP file",
    )
    _add_intake_arguments(intake_parser)

    verify_parser = subparsers.add_parser(
        "verify",
        help="re-verify registered evidence against its manifest",
    )
    verify_parser.add_argument(
        "evidence_id",
        nargs="?",
        help="evidence identifier; omit to verify every registration",
    )
    _add_common_arguments(verify_parser)

    return parser


def _add_common_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--root",
        default=DEFAULT_WORKSPACE_ROOT,
        help=f"evidence workspace directory (default: {DEFAULT_WORKSPACE_ROOT})",
    )


def _add_intake_arguments(parser: argparse.ArgumentParser) -> None:
    _add_common_arguments(parser)

    parser.add_argument("file", help="path to the submitted evidence file")

    parser.add_argument(
        "--source-identifier",
        default=None,
        help="submitting entity identifier, if supplied",
    )
    parser.add_argument(
        "--assessment-period",
        default=None,
        help="reporting period covered by the evidence, if supplied",
    )
    parser.add_argument(
        "--submitted-by",
        default=None,
        help="name of the submitter, if supplied",
    )
    parser.add_argument(
        "--received-channel",
        default=None,
        help="how the evidence was received, if supplied",
    )
    parser.add_argument(
        "--no-extract",
        action="store_true",
        help="register a ZIP package without extracting its members",
    )
    parser.add_argument(
        "--allow-duplicate",
        action="store_true",
        help="register byte-identical evidence that is already in the store",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="emit the intake record as JSON instead of a summary",
    )


def _run_intake(args: argparse.Namespace) -> int:
    intake = EvidenceIntake(root=args.root)

    record = intake.intake(
        args.file,
        source_identifier=args.source_identifier,
        assessment_period=args.assessment_period,
        submitted_by=args.submitted_by,
        received_channel=args.received_channel,
        extract_package=not args.no_extract,
        allow_duplicate=args.allow_duplicate,
    )

    if args.json:
        import json

        print(json.dumps(record.to_dict(), indent=2))

        return 0 if record.verified else 1

    print("[+] Evidence intake started")
    print(f"[+] Evidence ID: {record.evidence_id}")
    print(f"[+] File: {record.manifest.files[0].name}")
    print(f"[+] Size: {record.manifest.files[0].size} bytes")
    print(
        "[+] SHA-256 integrity fingerprint registered: "
        f"{record.manifest.files[0].sha256}"
    )
    print(f"[+] Original evidence preserved: {record.original_path}")
    print(
        "[+] Application-level write protection enabled: "
        f"{record.manifest.originals_read_only}"
    )
    print(f"[+] Working copy created: {record.working_path}")

    for name, _, written in record.package_members:
        print(f"[+] Package member extracted: {name} ({written} bytes)")

    print(f"[+] Manifest generated: {intake.manifest_path(record.evidence_id)}")
    print(
        f"[+] Provenance recorded: "
        f"{intake.provenance_path(record.evidence_id)}"
    )

    if record.provenance.unavailable_fields:
        print(
            "[!] Unavailable provenance fields: "
            + ", ".join(record.provenance.unavailable_fields)
        )

    print(f"[+] Integrity status: {record.integrity.status.value}")

    print(
        "[i] Locally stored evidence is not made physically immutable by "
        "this step: it is a registered SHA-256 fingerprint, and the original "
        "is preserved with application-level write protection only. A "
        "privileged filesystem user can still modify both the evidence and "
        "its manifest."
    )

    return 0 if record.verified else 1


def _run_verify(args: argparse.Namespace) -> int:
    intake = EvidenceIntake(root=args.root)

    if args.evidence_id:
        targets = [args.evidence_id]
    else:
        targets = intake.workspace.list_evidence_ids()

    if not targets:
        print("[!] No registered evidence to verify")

        return 0

    failed = False

    for evidence_id in targets:
        print(f"[+] Verifying {evidence_id}")

        for result in intake.verify(evidence_id):
            print(f"  {Path(result.path).name}: {result.status.value}")

            if result.expected_sha256:
                print(f"    Expected SHA-256: {result.expected_sha256}")

            if result.observed_sha256:
                print(f"    Observed SHA-256: {result.observed_sha256}")

            if not result.verified:
                failed = True

    return 1 if failed else 0


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Entry point for ``python -m framework.evidence.intake``."""

    arguments = list(sys.argv[1:] if argv is None else argv)

    # Bare `python -m framework.evidence.intake <file>` is the documented
    # shorthand for the `intake` sub-command.
    if arguments and arguments[0] not in ("intake", "verify", "-h", "--help"):
        arguments.insert(0, "intake")

    parser = _build_parser()
    args = parser.parse_args(arguments)

    if not args.command:
        parser.print_help()

        return 1

    try:
        if args.command == "intake":
            return _run_intake(args)

        return _run_verify(args)
    except EvidenceError as error:
        print(f"[!] {type(error).__name__}: {error}", file=sys.stderr)

        return 2


if __name__ == "__main__":
    sys.exit(main())
